--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: drupal-pvc
spec:
  storageClassName: "oci-bv" 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 5Gi
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: drupal-pvc-mysql
spec:
  storageClassName: "oci-bv" 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 5Gi


