---
- name: Install docker-compose
  gather_facts: false
  hosts: dockerserver
  user: opc
  become: yes

  tasks:
    - name: Install docker compose
      get_url:
         url: "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-Linux-x86_64"
         dest: /usr/local/bin/docker-compose
         mode: 0755

    



    